name: CI
on: [push, pull_request]
env:
  NODEJS_VERSION: ${{ secrets.NODEJS_VERSION }}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Using Variables
        run: |
          echo "$NODEJS_VERSION"
          echo $PR_NUMBER
          node --version

      # - uses: actions/checkout@v2
      # - name: Use Node.js $NODEJS_VERSION
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: $NODEJS_VERSION 
      # - name: npm install
        # run: |
          # npm install
      # - name: run Lighthouse CI
        # run: |
        #   npm install -g @lhci/cli@0.6.x
        #   lhci autorun